import { Montserrat } from "next/font/google";
import { NextAuthProvider } from "@/app/providers/NextAuthProvider";

const fontFamily = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body>
          <main className="mx-8 my-4">{children}</main>
        </body>
      </NextAuthProvider>
    </html>
  );
}
